
-- SEED DATA FOR BARANGAY OFFICIALS
-- Paste this into your Supabase SQL Editor to migrate hardcoded officials to the database.

INSERT INTO barangay_officials (slug, body) VALUES
('poblacion', '[{"name": "Hon. Roberto S. Tan", "position": "Kagawad"}, {"name": "Hon. Elena M. Reyes", "position": "Kagawad"}, {"name": "Hon. Mark A. Lim", "position": "Kagawad"}, {"name": "Hon. Sarah J. Co", "position": "Kagawad"}, {"name": "Hon. David L. Sy", "position": "Kagawad"}, {"name": "Hon. Grace P. Uy", "position": "Kagawad"}, {"name": "Hon. Michael B. Ang", "position": "Kagawad"}, {"name": "Ms. Jennifer T. Go", "position": "Secretary"}, {"name": "Mr. Nelson K. Chua", "position": "Treasurer"}, {"name": "Hon. Kevin B. Lee", "position": "SK Chairperson"}]'),
('san-jose', '[{"name": "Hon. Antonio P. Cruz", "position": "Kagawad"}, {"name": "Hon. Lucia R. Garcia", "position": "Kagawad"}, {"name": "Hon. Ricardo M. Diaz", "position": "Kagawad"}, {"name": "Hon. Felicia B. Ramos", "position": "Kagawad"}, {"name": "Hon. Jose S. Luna", "position": "Kagawad"}, {"name": "Hon. Teresa V. Blanco", "position": "Kagawad"}, {"name": "Hon. Manuel C. Reyes", "position": "Kagawad"}, {"name": "Ms. Anita L. Lopez", "position": "Secretary"}, {"name": "Mr. Gerardo M. Mendoza", "position": "Treasurer"}, {"name": "Hon. Paolo R. Santos", "position": "SK Chairperson"}]'),
('san-roque', '[{"name": "Hon. Feliciano M. Ortiz", "position": "Kagawad"}, {"name": "Hon. Rosenda S. Garcia", "position": "Kagawad"}, {"name": "Hon. Virgilio P. Ramos", "position": "Kagawad"}, {"name": "Hon. Leticia B. Cruz", "position": "Kagawad"}, {"name": "Hon. Rodolfo D. Santos", "position": "Kagawad"}, {"name": "Hon. Remedios L. Diaz", "position": "Kagawad"}, {"name": "Hon. Danilo C. Reyes", "position": "Kagawad"}, {"name": "Ms. Evelyn T. Blanco", "position": "Secretary"}, {"name": "Mr. Mario K. Lopez", "position": "Treasurer"}, {"name": "Hon. Bryan J. Lim", "position": "SK Chairperson"}]'),
('bagacay', '[{"name": "Hon. Sergio L. Mendez", "position": "Kagawad"}, {"name": "Hon. Gloria M. Torres", "position": "Kagawad"}, {"name": "Hon. Andres P. Silang", "position": "Kagawad"}, {"name": "Hon. Catalina B. Valenzuela", "position": "Kagawad"}, {"name": "Hon. Florencio D. Guevarra", "position": "Kagawad"}, {"name": "Hon. Teresita L. Roxas", "position": "Kagawad"}, {"name": "Hon. Wilfredo C. Laurel", "position": "Kagawad"}, {"name": "Ms. Josefina T. Aguinaldo", "position": "Secretary"}, {"name": "Mr. Benjamin K. Mabini", "position": "Treasurer"}, {"name": "Hon. Christian J. Bonifacio", "position": "SK Chairperson"}]'),
('balintawak', '[{"name": "Hon. Gregorio S. Del Pilar", "position": "Kagawad"}, {"name": "Hon. Marcela M. Agoncillo", "position": "Kagawad"}, {"name": "Hon. Juan P. Luna", "position": "Kagawad"}, {"name": "Hon. Gabriela B. Silang", "position": "Kagawad"}, {"name": "Hon. Marcelo D. H. Del Pilar", "position": "Kagawad"}, {"name": "Hon. Marina L. Dizon", "position": "Kagawad"}, {"name": "Hon. Mariano C. Alvarez", "position": "Kagawad"}, {"name": "Ms. Teresa T. Magbanua", "position": "Secretary"}, {"name": "Mr. Artemio K. Ricarte", "position": "Treasurer"}, {"name": "Hon. Emilio J. Jacinto", "position": "SK Chairperson"}]'),
('burgos', '[{"name": "Hon. Vicente S. Lim", "position": "Kagawad"}, {"name": "Hon. Josefa M. Escoda", "position": "Kagawad"}, {"name": "Hon. Manuel P. Quezon", "position": "Kagawad"}, {"name": "Hon. Teodora B. Alonso", "position": "Kagawad"}, {"name": "Hon. Sergio D. Osmeña", "position": "Kagawad"}, {"name": "Hon. Corazon L. Aquino", "position": "Kagawad"}, {"name": "Hon. Diosdado C. Macapagal", "position": "Kagawad"}, {"name": "Ms. Miriam T. Defensor", "position": "Secretary"}, {"name": "Mr. Juan K. Ponce", "position": "Treasurer"}, {"name": "Hon. Ferdinand J. Marcos", "position": "SK Chairperson"}]'),
('cabasacan', '[{"name": "Hon. Andres S. Bonifacio", "position": "Kagawad"}, {"name": "Hon. Gregoria M. De Jesus", "position": "Kagawad"}, {"name": "Hon. Emilio P. Aguinaldo", "position": "Kagawad"}, {"name": "Hon. Hilaria B. Del Rosario", "position": "Kagawad"}, {"name": "Hon. Apolinario D. Mabini", "position": "Kagawad"}, {"name": "Hon. Trinidad L. Tecson", "position": "Kagawad"}, {"name": "Hon. Antonio C. Luna", "position": "Kagawad"}, {"name": "Ms. Agueda T. Kahabagan", "position": "Secretary"}, {"name": "Mr. Macario K. Sakay", "position": "Treasurer"}, {"name": "Hon. Miguel J. Malvar", "position": "SK Chairperson"}]'),
('calituban', '[{"name": "Hon. Rajah S. Humabon", "position": "Kagawad"}, {"name": "Hon. Hara M. Amihan", "position": "Kagawad"}, {"name": "Hon. Kolambu P. Siagu", "position": "Kagawad"}, {"name": "Hon. Panglima B. Una", "position": "Kagawad"}, {"name": "Hon. Datu D. Puti", "position": "Kagawad"}, {"name": "Hon. Prinsesa L. Urduja", "position": "Kagawad"}, {"name": "Hon. Sultan C. Kudarat", "position": "Kagawad"}, {"name": "Ms. Dayang T. Kalangitan", "position": "Secretary"}, {"name": "Mr. Gat K. Selyo", "position": "Treasurer"}, {"name": "Hon. Bulalakaw J. Raymunda", "position": "SK Chairperson"}]'),
('cataban', '[{"name": "Hon. Francisco S. Sendrijas", "position": "Kagawad"}, {"name": "Hon. Juana M. Luna", "position": "Kagawad"}, {"name": "Hon. Diego P. Silang", "position": "Kagawad"}, {"name": "Hon. Josefa B. Llanes", "position": "Kagawad"}, {"name": "Hon. Juan D. Crisostomo", "position": "Kagawad"}, {"name": "Hon. Maria L. Clara", "position": "Kagawad"}, {"name": "Hon. Elias C. Ibarra", "position": "Kagawad"}, {"name": "Ms. Salome T. Fidel", "position": "Secretary"}, {"name": "Mr. Tasio K. Filosofo", "position": "Treasurer"}, {"name": "Hon. Basilio J. Crispin", "position": "SK Chairperson"}]'),
('guindacpan', '[{"name": "Hon. Humabon S. Raja", "position": "Kagawad"}, {"name": "Hon. Amihan M. Hara", "position": "Kagawad"}, {"name": "Hon. Siagu P. Kolambu", "position": "Kagawad"}, {"name": "Hon. Una B. Panglima", "position": "Kagawad"}, {"name": "Hon. Puti D. Datu", "position": "Kagawad"}, {"name": "Hon. Urduja L. Prinsesa", "position": "Kagawad"}, {"name": "Hon. Kudarat C. Sultan", "position": "Kagawad"}, {"name": "Ms. Kalangitan T. Dayang", "position": "Secretary"}, {"name": "Mr. Selyo K. Gat", "position": "Treasurer"}, {"name": "Hon. Raymunda J. Bulalakaw", "position": "SK Chairperson"}]'),
('magsaysay', '[{"name": "Hon. Luz S. Banzon", "position": "Kagawad"}, {"name": "Hon. Jesse M. Robredo", "position": "Kagawad"}, {"name": "Hon. Arsenio P. Lacson", "position": "Kagawad"}, {"name": "Hon. Maria B. Orosa", "position": "Kagawad"}, {"name": "Hon. Claro D. Recto", "position": "Kagawad"}, {"name": "Hon. Jose L. Diokno", "position": "Kagawad"}, {"name": "Hon. Jovito C. Salonga", "position": "Kagawad"}, {"name": "Ms. Haydee T. Yorac", "position": "Secretary"}, {"name": "Mr. Raul K. Roco", "position": "Treasurer"}, {"name": "Hon. Vico J. Sotto", "position": "SK Chairperson"}]'),
('mahanay', '[{"name": "Hon. Silvestre S. Bello", "position": "Kagawad"}, {"name": "Hon. Maria M. Lourdes", "position": "Kagawad"}, {"name": "Hon. Franklin P. Drilon", "position": "Kagawad"}, {"name": "Hon. Loren B. Legarda", "position": "Kagawad"}, {"name": "Hon. Richard D. Gordon", "position": "Kagawad"}, {"name": "Hon. Grace L. Poe", "position": "Kagawad"}, {"name": "Hon. Francis C. Pangilinan", "position": "Kagawad"}, {"name": "Ms. Risa T. Hontiveros", "position": "Secretary"}, {"name": "Mr. Bam K. Aquino", "position": "Treasurer"}, {"name": "Hon. Chel J. Diokno", "position": "SK Chairperson"}]'),
('nocnocan', '[{"name": "Hon. Nicanor S. Abelardo", "position": "Kagawad"}, {"name": "Hon. Atang M. Dela Rama", "position": "Kagawad"}, {"name": "Hon. Levi P. Celerio", "position": "Kagawad"}, {"name": "Hon. Honorata B. De La Rama", "position": "Kagawad"}, {"name": "Hon. Julian D. Felipe", "position": "Kagawad"}, {"name": "Hon. Dolores L. Paterno", "position": "Kagawad"}, {"name": "Hon. Jose C. Palma", "position": "Kagawad"}, {"name": "Ms. Lucresia T. Kasilag", "position": "Secretary"}, {"name": "Mr. Antonio K. Molina", "position": "Treasurer"}, {"name": "Hon. Ryan J. Cayabyab", "position": "SK Chairperson"}]'),
('nueva-esperanza', '[{"name": "Hon. Angel S. Locsin", "position": "Kagawad"}, {"name": "Hon. Piolo M. Pascual", "position": "Kagawad"}, {"name": "Hon. Bea P. Alonzo", "position": "Kagawad"}, {"name": "Hon. John D. Lloyd", "position": "Kagawad"}, {"name": "Hon. Marian L. Rivera", "position": "Kagawad"}, {"name": "Hon. Dingdong C. Dantes", "position": "Kagawad"}, {"name": "Hon. Anne J. Curtis", "position": "Kagawad"}, {"name": "Ms. Kathryn T. Bernardo", "position": "Secretary"}, {"name": "Mr. Daniel K. Padilla", "position": "Treasurer"}, {"name": "Hon. Liza J. Soberano", "position": "SK Chairperson"}]'),
('rizal', '[{"name": "Hon. Narcisa S. Rizal", "position": "Kagawad"}, {"name": "Hon. Paciano M. Rizal", "position": "Kagawad"}, {"name": "Hon. Olympia P. Rizal", "position": "Kagawad"}, {"name": "Hon. Lucia B. Rizal", "position": "Kagawad"}, {"name": "Hon. Maria D. Rizal", "position": "Kagawad"}, {"name": "Hon. Jose L. Rizal", "position": "Kagawad"}, {"name": "Hon. Concepcion C. Rizal", "position": "Kagawad"}, {"name": "Ms. Josefa T. Rizal", "position": "Secretary"}, {"name": "Mr. Trinidad K. Rizal", "position": "Treasurer"}, {"name": "Hon. Soledad J. Rizal", "position": "SK Chairperson"}]'),
('sag', '[{"name": "Hon. Carlos S. P. Romulo", "position": "Kagawad"}, {"name": "Hon. Helena M. Benitez", "position": "Kagawad"}, {"name": "Hon. Jose P. Laurel", "position": "Kagawad"}, {"name": "Hon. Rafael B. Salas", "position": "Kagawad"}, {"name": "Hon. Blas D. Ople", "position": "Kagawad"}, {"name": "Hon. Leticia L. Shahani", "position": "Kagawad"}, {"name": "Hon. Narciso C. Ramos", "position": "Kagawad"}, {"name": "Ms. Solita T. Monsod", "position": "Secretary"}, {"name": "Mr. Felipe K. Gozon", "position": "Treasurer"}, {"name": "Hon. Manny J. Pangilinan", "position": "SK Chairperson"}]'),
('san-agustin', '[{"name": "Hon. Monica S. Agustin", "position": "Kagawad"}, {"name": "Hon. Aurelius M. Agustin", "position": "Kagawad"}, {"name": "Hon. Ambrose P. Agustin", "position": "Kagawad"}, {"name": "Hon. Jerome B. Agustin", "position": "Kagawad"}, {"name": "Hon. Gregory D. Agustin", "position": "Kagawad"}, {"name": "Hon. Bernard L. Agustin", "position": "Kagawad"}, {"name": "Hon. Francis C. Agustin", "position": "Kagawad"}, {"name": "Ms. Clara T. Agustin", "position": "Secretary"}, {"name": "Mr. Dominic K. Agustin", "position": "Treasurer"}, {"name": "Hon. Therese J. Agustin", "position": "SK Chairperson"}]'),
('san-francisco', '[{"name": "Hon. Sarah S. Geronimo", "position": "Kagawad"}, {"name": "Hon. Matteo M. Guidicelli", "position": "Kagawad"}, {"name": "Hon. Billy P. Crawford", "position": "Kagawad"}, {"name": "Hon. Coleen B. Garcia", "position": "Kagawad"}, {"name": "Hon. Luis D. Manzano", "position": "Kagawad"}, {"name": "Hon. Jessy L. Mendiola", "position": "Kagawad"}, {"name": "Hon. Dingdong C. Avanzado", "position": "Kagawad"}, {"name": "Ms. Jessa T. Zaragoza", "position": "Secretary"}, {"name": "Mr. Ogie K. Alcasid", "position": "Treasurer"}, {"name": "Hon. Regine J. Velasquez", "position": "SK Chairperson"}]'),
('san-isidro', '[{"name": "Hon. Isidra S. Labrador", "position": "Kagawad"}, {"name": "Hon. Farmer M. Juan", "position": "Kagawad"}, {"name": "Hon. Harvest P. Pedro", "position": "Kagawad"}, {"name": "Hon. Rice B. Maria", "position": "Kagawad"}, {"name": "Hon. Corn D. Jose", "position": "Kagawad"}, {"name": "Hon. Field L. Ana", "position": "Kagawad"}, {"name": "Hon. Green C. Manuel", "position": "Kagawad"}, {"name": "Ms. Bloom T. Flora", "position": "Secretary"}, {"name": "Mr. Seed K. Sower", "position": "Treasurer"}, {"name": "Hon. Growth J. Root", "position": "SK Chairperson"}]'),
('san-pedro', '[{"name": "Hon. Petra S. Rock", "position": "Kagawad"}, {"name": "Hon. Paul M. Apostle", "position": "Kagawad"}, {"name": "Hon. Andrew P. Fisherman", "position": "Kagawad"}, {"name": "Hon. James B. Zebedee", "position": "Kagawad"}, {"name": "Hon. John D. Beloved", "position": "Kagawad"}, {"name": "Hon. Philip L. Deacon", "position": "Kagawad"}, {"name": "Hon. Thomas C. Twin", "position": "Kagawad"}, {"name": "Ms. Martha T. Sister", "position": "Secretary"}, {"name": "Mr. Lazarus K. Risen", "position": "Treasurer"}, {"name": "Hon. Mary J. Magdalene", "position": "SK Chairperson"}]'),
('santo-nino', '[{"name": "Hon. Child S. Holy", "position": "Kagawad"}, {"name": "Hon. Faith M. Hope", "position": "Kagawad"}, {"name": "Hon. Love P. Charity", "position": "Kagawad"}, {"name": "Hon. Joy B. Peace", "position": "Kagawad"}, {"name": "Hon. Kindness D. Goodness", "position": "Kagawad"}, {"name": "Hon. Gentleness L. Patience", "position": "Kagawad"}, {"name": "Hon. Wisdom C. Knowledge", "position": "Kagawad"}, {"name": "Ms. Grace T. Mercy", "position": "Secretary"}, {"name": "Mr. Praise K. Glory", "position": "Treasurer"}, {"name": "Hon. Honor J. Victory", "position": "SK Chairperson"}]'),
('sikatuna', '[{"name": "Hon. Katunao S. Rajah", "position": "Kagawad"}, {"name": "Hon. Legazpi M. Miguel", "position": "Kagawad"}, {"name": "Hon. Sandugo P. Compact", "position": "Kagawad"}, {"name": "Hon. Friendship B. Union", "position": "Kagawad"}, {"name": "Hon. Pact D. Blood", "position": "Kagawad"}, {"name": "Hon. Peace L. Treaty", "position": "Kagawad"}, {"name": "Hon. History C. Legacy", "position": "Kagawad"}, {"name": "Ms. Heritage T. Culture", "position": "Secretary"}, {"name": "Mr. Museum K. Gallery", "position": "Treasurer"}, {"name": "Hon. Future J. Vision", "position": "SK Chairperson"}]'),
('suba', '[{"name": "Hon. River S. Flow", "position": "Kagawad"}, {"name": "Hon. Stream M. Current", "position": "Kagawad"}, {"name": "Hon. Bridge P. Crossing", "position": "Kagawad"}, {"name": "Hon. Water B. Life", "position": "Kagawad"}, {"name": "Hon. Delta D. Mouth", "position": "Kagawad"}, {"name": "Hon. Canal L. Pathway", "position": "Kagawad"}, {"name": "Hon. Bank C. Side", "position": "Kagawad"}, {"name": "Ms. Tide T. Wave", "position": "Secretary"}, {"name": "Mr. Rapid K. Speed", "position": "Treasurer"}, {"name": "Hon. Ocean J. Deep", "position": "SK Chairperson"}]'),
('tanghaligue', '[{"name": "Hon. Noon S. Day", "position": "Kagawad"}, {"name": "Hon. Bright M. Light", "position": "Kagawad"}, {"name": "Hon. Peak P. Height", "position": "Kagawad"}, {"name": "Hon. Sun B. Rays", "position": "Kagawad"}, {"name": "Hon. Sky D. High", "position": "Kagawad"}, {"name": "Hon. Zenith L. Top", "position": "Kagawad"}, {"name": "Hon. Summit C. Crest", "position": "Kagawad"}, {"name": "Ms. Aurora T. Dawn", "position": "Secretary"}, {"name": "Mr. Dusk K. Night", "position": "Treasurer"}, {"name": "Hon. Star J. Shine", "position": "SK Chairperson"}]'),
('zamura', '[{"name": "Hon. Jacinto S. Zamora", "position": "Kagawad"}, {"name": "Hon. Mariano M. Gomes", "position": "Kagawad"}, {"name": "Hon. Jose P. Burgos", "position": "Kagawad"}, {"name": "Hon. Gomburza B. Unity", "position": "Kagawad"}, {"name": "Hon. Martyr D. Hero", "position": "Kagawad"}, {"name": "Hon. Freedom L. Liberty", "position": "Kagawad"}, {"name": "Hon. Justice C. Right", "position": "Kagawad"}, {"name": "Ms. Peace T. Quiet", "position": "Secretary"}, {"name": "Mr. Nature K. Field", "position": "Treasurer"}, {"name": "Hon. Forest J. Tree", "position": "SK Chairperson"}]')
ON CONFLICT (slug) DO UPDATE SET body = EXCLUDED.body;
